[swift][swift-testing]
=== swift ================================================
[DebuggingTheCompiler.md] Add link to Swift Testing LLDB command-line debugging docs

=== swift-testing ========================================
FreeBSD: bsearch pointer is Nonnull (#1505)
The pointer passed into the compare function is marked Nonnull in the
FreeBSD stdlib header. This causes a build failure due to the unwrap.

```
error: cannot force unwrap value of non-optional type 'UnsafeRawPointer'
```

Fixing it for FreeBSD.