[llvm-project][swift][swift-foundation][swift-testing]
=== llvm-project =========================================
Merge pull request #12234 from ndrewh/cherry-pick-sanitizer-warning-fix
[cherry-pick] [sanitizers] [Darwin] Fix erroneous warning when external_symbolizer_path=""

=== swift ================================================
Prepare for strict enforcement of conditionally Escapable
The only intended functional change is that a diagnostic message is split into
an error and a note:

    error: cannot copy the lifetime of an Escapable type
    note: use '@_lifetime(borrow arg)' instead

Reorganize the LifetimeDependenceChecker to support adding the functionality
required for strict enforcement.

Adds parameter index to ParamInfo.

Adds a few (temporarily unused) helper methods.

=== swift-foundation =====================================
(166098325) Fix resolution for fragment-only relative URLs (#1702)

=== swift-testing ========================================
Fix typo